/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasakhir;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ACER NITRO
 */
public class Peminjaman extends javax.swing.JFrame {
    private Connection koneksi;
    
 public void tanggal(){
        Date tgl = new Date();
        tglPinjam.setDate(tgl);
    }

 
 
    /**
     * Creates new form Peminjaman
     */
    public Peminjaman() {
        initComponents();
        koneksiDatabase();
        tanggal();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        cbAnggota();
        cbBuku();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbAnggota = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbBuku = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tglKembali = new com.toedter.calendar.JDateChooser();
        btnSimpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKet = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        tglPinjam = new com.toedter.calendar.JDateChooser();
        txtKode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Formulir Peminjaman Buku"));

        jLabel2.setText("ID Anggota");

        jLabel3.setText("Nama Anggota");

        cbAnggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------------Pilih ID Anggota---------------" }));
        cbAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnggotaActionPerformed(evt);
            }
        });

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel4.setText("Judul Buku");

        cbBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Silakan pilih buku yang akan dipinjam---" }));
        cbBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBukuActionPerformed(evt);
            }
        });

        jLabel5.setText("Tanggal Peminjaman");

        jLabel6.setText("Batas Pengembalian");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("Keterangan");

        txtKet.setColumns(20);
        txtKet.setRows(5);
        jScrollPane1.setViewportView(txtKet);

        jButton4.setText("Batal");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("HYWenHei-85W", 0, 11)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Catatan :\n- Masa peminjaman buku adalah selama 7 hari.\n- Denda keterlambatan pengembalian buku dikenakan sebesar Rp 500 per hari.\n- Buku yang hilang atau rusak harus diganti dengan buku yang sama atau membayar denda sesuai dengan nilai buku.\n");
        jScrollPane3.setViewportView(jTextArea2);

        tglPinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglPinjamPropertyChange(evt);
            }
        });

        txtKode.setEditable(false);

        jLabel8.setText("Kode Buku");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbBuku, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNama)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbAnggota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(tglPinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 56, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addContainerGap())))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card2");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Riwayat Peminjaman Buku"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Peminjaman", "ID Anggota", "Nama Anggota", "Judul Buku", "Tanggal Peminjaman", "Batas Peminjaman", "Keterangan"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, "card3");

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("HYWenHei-85W", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PERPUSTAKAAN KUKUS");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Custom-Icon-Design-Pretty-Office-5-Undo.256 (1).png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setText("Formulir Peminjaman Buku");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Riwayat Peminjaman Buku");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(525, 525, 525))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 jPanel2.removeAll();
    jPanel2.add(jPanel3);
    jPanel2.revalidate();
    jPanel2.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     jPanel2.removeAll();
    jPanel2.add(jPanel4);
    jPanel2.revalidate();
    jPanel2.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     new menu().setVisible(true);
     this.dispose();  
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cbAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnggotaActionPerformed
Object selectedSiswaObj = cbAnggota.getSelectedItem();
    if (selectedSiswaObj != null) {
        String selectedSiswa = selectedSiswaObj.toString();
        if (!selectedSiswa.equals("---------------Pilih ID Anggota---------------")) {
            try {
                String sqlNIS = "SELECT `Nama Anggota` FROM siswa WHERE `NIS` = ?";
                java.sql.PreparedStatement statNama = koneksi.prepareStatement(sqlNIS);
                statNama.setString(1, selectedSiswa);
                ResultSet dataNama = statNama.executeQuery();
                if (dataNama.next()) {
                    String nama = dataNama.getString("Nama Anggota");
                    txtNama.setText(nama);
                }
                statNama.close();
            } catch (Exception e) {
                System.err.println("Terjadi Kesalahan :" + e);
            }
        } else {
            txtNama.setText(""); // Kosongkan txtNIS jika pilihan "---------------Pilih Anggota---------------" dipilih
        }
}     
    }//GEN-LAST:event_cbAnggotaActionPerformed

    private void tglPinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglPinjamPropertyChange
    if ("date".equals(evt.getPropertyName())) {
        Date tglPinjam = (Date) evt.getNewValue();
        if (tglPinjam != null) {
            // Membuat instance Calendar dan mengatur dengan tanggal pinjam
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(tglPinjam);

            // Menambahkan 7 hari ke tanggal pinjam
            calendar.add(Calendar.DAY_OF_MONTH, 7);

            // Mengatur tanggal kembali menjadi 7 hari setelah tanggal pinjam
            Date tglKembali1 = calendar.getTime();

            // Mengatur tanggal pada tglKembaliChooser
            tglKembali.setDate(tglKembali1);
        }
    }
    }//GEN-LAST:event_tglPinjamPropertyChange

    private void cbBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBukuActionPerformed
Object selectedSiswaObj = cbBuku.getSelectedItem();
    if (selectedSiswaObj != null) {
        String selectedSiswa = selectedSiswaObj.toString();
        if (!selectedSiswa.equals("---Silakan pilih buku yang akan dipinjam---")) {
            try {
                String sqlJudul = "SELECT `kode_buku` FROM buku WHERE `judul` = ?";
                java.sql.PreparedStatement statKode = koneksi.prepareStatement(sqlJudul);
                statKode.setString(1, selectedSiswa);
                ResultSet dataKode = statKode.executeQuery();
                if (dataKode.next()) {
                    String kode = dataKode.getString("kode_buku");
                    txtKode.setText(kode);
                }
                statKode.close();
            } catch (Exception e) {
                System.err.println("Terjadi Kesalahan :" + e);
            }
        } else {
            txtKode.setText(""); // Kosongkan txtNIS jika pilihan "---------------Pilih Anggota---------------" dipilih
        }
    }        
    }//GEN-LAST:event_cbBukuActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    String id = (String) cbAnggota.getSelectedItem();
    String nama     = txtNama.getText();
    String judul= (String) cbBuku.getSelectedItem();
    String kode   = txtKode.getText();
               SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd"); 
            String tanggalpinjam = String.valueOf(fm.format(tglPinjam.getDate()));
            String bataskembali = String.valueOf(fm.format(tglKembali.getDate()));
    String keterangan = txtKet.getText();
       try {
        java.sql.Statement stat = koneksi.createStatement();
        // Periksa jumlah buku
        String checkJumlahBukuQuery = "SELECT jumlah FROM buku WHERE kode_buku = ?";
        java.sql.PreparedStatement pstCheckJumlah = koneksi.prepareStatement(checkJumlahBukuQuery);
        pstCheckJumlah.setString(1, kode);
        java.sql.ResultSet rsJumlah = pstCheckJumlah.executeQuery();
        
        if (rsJumlah.next()) {
            int jumlahBuku = rsJumlah.getInt("jumlah");
            if (jumlahBuku <= 0) {
                JOptionPane.showMessageDialog(null, "buku habis. Tidak bisa meminjam buku ini.", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        // Mengambil ID terakhir yang ada di tabel peminjaman
        String getLastIdQuery = "SELECT id_peminjaman FROM peminjaman ORDER BY id_peminjaman DESC LIMIT 1";
        java.sql.ResultSet rs = stat.executeQuery(getLastIdQuery);
        String newId;
        if (rs.next()) {
            String lastId = rs.getString("id_peminjaman");
            int lastNum = Integer.parseInt(lastId.substring(3)); // Mengambil angka dari PPKXXX
            newId = String.format("PPK%03d", lastNum + 1);
        } else {
            newId = "PPK001"; // Jika tidak ada data, mulai dari PPK001
        }    
        // Menyimpan data ke tabel peminjaman menggunakan PreparedStatement
        String sql = "INSERT INTO peminjaman (id_peminjaman, id_anggota, nama_peminjam, judul_buku, kode_buku, tgl_peminjaman, batas_pengembalian, tgl_kembali, keterangan) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        java.sql.PreparedStatement pst = koneksi.prepareStatement(sql);
        pst.setString(1, newId);
        pst.setString(2, id);
        pst.setString(3, nama);
        pst.setString(4, judul);
        pst.setString(5, kode);
        pst.setString(6, tanggalpinjam);
        pst.setString(7, bataskembali);
        pst.setNull(8, java.sql.Types.DATE);
        pst.setString(9, keterangan);
        
        pst.executeUpdate();
        
          // Mengurangi jumlah buku dalam tabel buku
        String updateBukuSql = "UPDATE buku SET jumlah = jumlah - 1 WHERE kode_buku = ?";
        java.sql.PreparedStatement pstUpdateBuku = koneksi.prepareStatement(updateBukuSql);
        pstUpdateBuku.setString(1, kode);
        pstUpdateBuku.executeUpdate();
        
        JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
        
        // Tutup statement dan bersihkan form
        pst.close();
        stat.close();
        bersihkan();
        tampilData();
        
    } catch (Exception exc) {
        System.err.println("Terjadi Kesalahan Simpan: " + exc);
        JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Saat Menyimpan Data", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbAnggota;
    private javax.swing.JComboBox<String> cbBuku;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private com.toedter.calendar.JDateChooser tglKembali;
    private com.toedter.calendar.JDateChooser tglPinjam;
    private javax.swing.JTextArea txtKet;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    private void koneksiDatabase() {
           try {
          Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException cnf) {
        }
        try {
            koneksi = DriverManager.getConnection("jdbc:mysql://localhost/itoko", "root", "");
        } catch (SQLException se) {
            JOptionPane.showMessageDialog(null, "Koneksi Database Tidak Berhasil");
        } catch (Exception e) {
        } 
    }

    private void cbAnggota() {
        try {
        String sql = "SELECT `NIS` FROM siswa";
        java.sql.PreparedStatement stat = koneksi.prepareStatement(sql);
        ResultSet data = stat.executeQuery();

        cbAnggota.removeAllItems(); // Menghapus item sebelumnya
        cbAnggota.addItem("---------------Pilih ID Anggota---------------"); // Menambahkan pilihan default

        while (data.next()) {
            String siswa = data.getString("NIS");
            cbAnggota.addItem(siswa);
        }

        stat.close();
    } catch (Exception e) {
        System.err.println("Terjadi Kesalahan :" + e);
    }
}

    private void cbBuku() {
       try {
        String sql = "SELECT `judul` FROM buku";
        java.sql.PreparedStatement stat = koneksi.prepareStatement(sql);
        ResultSet data = stat.executeQuery();

        cbBuku.removeAllItems(); // Menghapus item sebelumnya
        cbBuku.addItem("---Silakan pilih buku yang akan dipinjam---"); // Menambahkan pilihan default

        while (data.next()) {
            String siswa = data.getString("judul");
            cbBuku.addItem(siswa);
        }

        stat.close();
    } catch (Exception e) {
        System.err.println("Terjadi Kesalahan :" + e);
    }
}

    private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Peminjaman");
        model.addColumn("ID Anggota");
        model.addColumn("Nama Anggota");
        model.addColumn("Judul Buku");
        model.addColumn("Tanggal Peminjaman");
         model.addColumn("Batas Pengembalian");
         model.addColumn("Keterangan");
         
        jTable1.setModel(model);
        try {
            java.sql.Statement stat = koneksi.createStatement();
            ResultSet data = stat.executeQuery("SELECT * FROM peminjaman");
            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString("id_peminjaman"),
                    data.getString("id_anggota"),
                    data.getString("nama_peminjam"),
                    data.getString("judul_buku"),
                    data.getString("tgl_peminjaman"),
                    data.getString("batas_pengembalian"),
                    data.getString("keterangan")
                });
                jTable1.setModel(model);
            }        
        } catch (Exception e) {
            System.err.println("Terjadi Kesalahan :" + e);
        }        
    }

    private void bersihkan() {
         cbAnggota.setSelectedIndex(0);
          cbBuku.setSelectedIndex(0);
          txtKet.setText(null);
        }
}